FROM pytorch/pytorch:latest

RUN apt update
RUN apt install -y wget git curl libsndfile1

RUN useradd --create-home user
USER user
RUN mkdir /home/user/data 

WORKDIR /home/user/data/

RUN pip install --upgrade pip
RUN pip install telekinesis
COPY script.py ../src/

{{PKG_DEPENDENCIES}}

ENTRYPOINT ["python", "../src/script.py"]