FROM node:18-buster-slim

RUN apt update
RUN apt install -y wget git curl

RUN useradd --create-home user
USER user
RUN mkdir /home/user/data
RUN mkdir /home/user/src

WORKDIR /home/user/src

RUN npm install npm@8.5.4
RUN npm install telekinesis-js ws
COPY script.js .

{{PKG_DEPENDENCIES}}

WORKDIR /home/user/data

ENTRYPOINT ["node", "../src/script.js"]