FROM python:3.10-slim-buster

RUN apt update
RUN apt install -y wget curl gnupg unzip libgconf-2-4 xvfb
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

RUN useradd --create-home user
USER user
RUN mkdir /home/user/data

WORKDIR /home/user/data/

RUN pip install --upgrade pip
RUN pip install telekinesis selenium
COPY script.py ../src/

{{PKG_DEPENDENCIES}}

ENTRYPOINT ["python", "../src/script.py"]